### ISSUE TITLE
BazelでGoをビルドできるように

### ISSUE THREAD

**Issue by aokabin** [aokabin/bazel-practice#2]
rules_goを取り込む必要がありそう
- [bazelbuild/rules\_go: Go rules for Bazel](https://github.com/bazelbuild/rules_go)
- [golangとbazelで作るいい感じなビルド環境 \- Devlion Memo](http://mjhd.hatenablog.com/entry/2018/07/22/224528)

**Comment by aokabin** [comment]
rules_goのドキュメント読んでみる

- WORKSPACEという名前のリポジトリの最上部にファイルを作成し、以下のスニペットの1つを逐語的に追加します。これによりBazelはこのリポジトリと他のいくつかから必要な依存関係を取得することができます。

これは普通にBazelの使い方ぽい

```bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.1/rules_go-0.18.1.tar.gz"],
    sha256 = "77dfd303492f2634de7a660445ee2d3de2960cbd52f97d8c0dffa9362d3ddef9",
)
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
```

これにより、最新版のstableな奴が使えるらしい
欲しいのがあったらそのcommitを選べば良いとのこと
- [bazelbuild/rules\_go: Go rules for Bazel #Setup](https://github.com/bazelbuild/rules_go#setup)

> プロジェクトのルートディレクトリにBUILD.bazelという名前のファイルを追加します。一般に、Goコードを含む各ディレクトリにこれらのファイルの1つが必要ですが、プロジェクトにGoコードがない場合でも、ルートディレクトリに1つ必要です。

とのこと

**Comment by aokabin** [comment]
> プロジェクトをgo buildでビルドできる場合は、Gazelleを使ってビルドファイルを生成できます。あなたのプロジェクトがgo buildと互換性がない場合、またはGazelleを使用したくない場合は、手動でビルドファイルを書くことができます。

つまりgo buildと互換性があるならGazelleを使えば良さそう

**Comment by aokabin** [comment]
> プロジェクトをgo buildでビルドできる場合は、gazelleを使ってビルドファイルを自動的に生成および更新できます。
> go_rules_dependenciesが呼び出される前に、bazel_gazelleリポジトリとその依存関係をWORKSPACEファイルに追加します。これは次のようになります。

```bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.1/rules_go-0.18.1.tar.gz"],
    sha256 = "77dfd303492f2634de7a660445ee2d3de2960cbd52f97d8c0dffa9362d3ddef9",
)
http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
)
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()
```

> 以下のコードを、リポジトリのルートディレクトリにあるBUILDまたはBUILD.bazelファイルに追加してください。接頭辞の後の文字列を、プロジェクトで以前に選択した接頭辞で置き換えます。

```bzl
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/example/project
gazelle(name = "gazelle")
```

追加したら以下

```bash
bazel run //:gazelle
```

> これはあなたのリポジトリの各Goパッケージに対してBUILD.bazelファイルを生成します。将来同じコマンドを実行して、既存のビルドファイルを新しいソースファイル、依存関係、およびオプションで更新することができます。

便利そう

**Comment by aokabin** [comment]
なお、手動でbuildする場合はこちら→[bazelbuild/rules\_go: Go rules for Bazel #Writing build files by hand](https://github.com/bazelbuild/rules_go#writing-build-files-by-hand)

### 外部リポジトリを追加する場合

> Goリポジトリごとに、以下のようなgo_repositoryルールを追加します。このルールはGazelleリポジトリから来ているので、ロードする必要があります。 `gazelle update-repos` はgo.modまたはGopkg.lockファイルからこれらのルールを自動的に生成または更新できます。

`gazelle update-repos`とかのように、gazelleのコマンドとかもあるらしい
- [bazelbuild/bazel\-gazelle: Gazelle is a Bazel build file generator for Go projects\.](https://github.com/bazelbuild/bazel-gazelle#update-repos)

```bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Download the Go rules
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.1/rules_go-0.18.1.tar.gz"],
    sha256 = "77dfd303492f2634de7a660445ee2d3de2960cbd52f97d8c0dffa9362d3ddef9",
)

# Load and call the dependencies
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

# Download Gazelle
http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
)

# Load and call Gazelle dependencies
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
gazelle_dependencies()

# Add a go repository
go_repository(
    name = "com_github_pkg_errors",
    importpath = "github.com/pkg/errors", # Import path used in the .go files
    tag = "v0.8.1",                       # Specific tag, commits are also supported
)
```

ん...？外部リポジトリってなんだ...？

**Comment by aokabin** [comment]
とりあえず一度ビルドして実行してみる
→ 失敗する

```
bazel run //cmd/sample:go_image
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_kd/39a3b0c53b1a0bacc87f91f861c738fc/external/io_bazel_rules_go/go/private/tools/path.bzl:160:17: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_kd/39a3b0c53b1a0bacc87f91f861c738fc/external/io_bazel_rules_go/go/private/tools/path.bzl", line 156
		rule(_go_path_impl, attrs = {"deps": at...")})
	File "/private/var/tmp/_bazel_kd/39a3b0c53b1a0bacc87f91f861c738fc/external/io_bazel_rules_go/go/private/tools/path.bzl", line 160, in rule
		attr.label_list(allow_files = True, cfg = "data")
Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
ERROR: error loading package '': in /private/var/tmp/_bazel_kd/39a3b0c53b1a0bacc87f91f861c738fc/external/io_bazel_rules_go/go/def.bzl: Extension file 'go/private/tools/path.bzl' has errors
ERROR: error loading package '': in /private/var/tmp/_bazel_kd/39a3b0c53b1a0bacc87f91f861c738fc/external/io_bazel_rules_go/go/def.bzl: Extension file 'go/private/tools/path.bzl' has errors
INFO: Elapsed time: 3.691s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
make: *** [run] Error 1ls /private/var/tmp/_bazel_kd/code
```

何か問題が起きているな....

バージョンを上げてみる

```bzl
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.18.1/rules_go-0.18.1.tar.gz",
    sha256 = "77dfd303492f2634de7a660445ee2d3de2960cbd52f97d8c0dffa9362d3ddef9",
)

http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "aed1c249d4ec8f703edddf35cbe9dfaca0b5f5ea6e4cd9e83e99f3b0d1136c3d",
    strip_prefix = "rules_docker-0.7.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.7.0.tar.gz"],
)
```

```
bazel run //cmd/sample:go_image --incompatible_disallow_data_transition=false
ERROR: Failed to load Starlark extension '@io_bazel_rules_go_compat//:compat.bzl'.
It usually happens when the repository is not defined prior to being used.
This could either mean you have to add the 'io_bazel_rules_go_compat' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or the repository 'io_bazel_rules_go_compat' was defined too late in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.281s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

エラーが変わった

**Comment by aokabin** [comment]
> It usually happens when the repository is not defined prior to being used.
> This could either mean you have to add the 'io_bazel_rules_go_compat' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or the repository 'io_bazel_rules_go_compat' was defined too late in your WORKSPACE file.

日本語に訳すと

> 通常、リポジトリが使用前に定義されていない場合に発生します。
> これは、あなたのWORKSPACEファイルに `io_bazel_rules_go_compat 'レポジトリを` http_archive`のようなステートメントで追加する必要があることを意味します（推移的な依存関係は自動的に追加されないことに注意してください）。

compatがないじゃーんってことかな

解決した

```bzl
# こっち
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
# じゃなくて、こっち↓
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
```

def.bzlじゃなくてdeps.bzl

どうもタイポ(？あるいは元々はこうだったのかもしれないけど)があったみたい
- [compatibility layer · Issue \#1937 · bazelbuild/rules\_go](https://github.com/bazelbuild/rules_go/issues/1937)

**Comment by aokabin** [comment]
うまくビルドできた！のでどういう構造なのかを読んでみる

Makefileの中身はこんな感じ
```Makefile
.PHONY: run
run:
	bazel run //cmd/sample:go_image

.PHONY: build
build:
	bazel build //cmd/sample:go_image

.PHONY: test
test:
	bazel test //...

.PHONY: gazelle
gazelle:
	bazel run //:gazelle -- update-repos -from_file ./Gopkg.lock

```

で、makeするとこうなる

```bash
bazel run //cmd/sample:go_image
INFO: Analysed target //cmd/sample:go_image (51 packages loaded, 6815 targets configured).
INFO: Found 1 target...
Target //cmd/sample:go_image up-to-date:
  bazel-bin/cmd/sample/go_image-layer.tar
INFO: Elapsed time: 8.152s, Critical Path: 0.21s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Loaded image ID: sha256:8990ac013637d9655ba06eb7c218306bcd5a00b5724225ba399570f7426fb530
Tagging 8990ac013637d9655ba06eb7c218306bcd5a00b5724225ba399570f7426fb530 as bazel/cmd/sample:go_image
{
  "foo":   "bar",
  "hello": "world",
}
```

go_imageを読んでみよう

**Comment by aokabin** [comment]
```bzl
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_docker//go:image.bzl", "go_image")

go_image(
    name = "go_image",
    embed = [":go_default_library"],
    goarch = "amd64",
    goos = "linux",
    importpath = "github.com/mjhd-devlion/bazel-gazelle-sample",
    pure = "on",
)

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/mjhd-devlion/bazel-gazelle-sample/cmd/sample",
    visibility = ["//visibility:private"],
    deps = ["//pkg/sample:go_default_library"],
)
```

go_libraryとgo_imageは`io_bazel_ryules_go`と`io_bazel_rules_docker`から持ってきているっぽい

挙動がどうなっているかはこの辺り
- [go_library](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-library)
- [go_image](https://github.com/bazelbuild/rules_docker/#go_image)

**Comment by aokabin** [comment]
ビルドの流れとかGoにちょっと詳しくなるまで一旦Stopしようかな
- [GoとBazel – Jun Mukai's blog](https://wp.jmuk.org/2017/09/21/go%E3%81%A8bazel/)

なお`bazel-gazelle-sample`をやっている途中
